### ISSUE TITLE
GIS endpoint returning 0 results

### ISSUE THREAD

**Issue by mejarc** [bureau-of-information/mopd#2]
**What I did:** load https://bureau-of-information.github.io/mopd/ in Firefox, on July 28, 2024

**What I expected:** the usual list of Oakland-specific mayhem

**What happened instead:** the call to _https://gismaps.oaklandca.gov/oaklandgis/rest/services/callforservice_2015_FC/MapServer/0/query?f=json&returnIdsOnly=true&returnCountOnly=true&where=I_STATUSID%3D%27A%27&returnGeometry=false&spatialRel=esriSpatialRelIntersects&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback_

returns 0 results. 
![Screenshot 2024-07-28 at 11 37 38 AM](https://github.com/user-attachments/assets/5e06d8fe-6d0e-4b82-8cd8-997172bb2ff4)

**Comment by bureau-of-information** [comment]
Thanks for reporting.

This is a problem with the City of Oakland's Calls for Sevice feed (the original data source). It fails regularly and tends to stay down for weeks after. Last time it was down, it took about 6 weeks for someone to fix. The time before that, it took about two weeks. 

The issue has been reported to the City. The feed went down the same day as the CrowdStrike issue so possibly related.

If you go to the City's Calls for Service tool (https://gisapps1.mapoakland.com/callsforservice/) and also see no results, the issue is outside of our control.
